### ISSUE TITLE
is it possible to do inpaint conditioned on another image?

### ISSUE THREAD

**Issue by themrzmaster** [mikonvergence/ControlNetInpaint#1]
Instead on conditioning on a text prompt, can we somehow use controlnet to condition on another image and replace an masked area with this new image? 

Thanks

**Comment by mikonvergence** [comment]
Yes, and there are many ways to achieve that.

First, you can turn off the text prompt by either using an empty string `""` or by setting the parameter of `guidance_scale=0.0` (as explained in the documentation, this corresponds to the strength of text guidance).

For mixing two images, you can potentially do the following:
1. Combine the two images using the mask, yielding a composite image
2. Extract ControlNet guidance, such as canny edge (as shown in the example notebook), from the composite image
3. To the ControlNetInpaint pipeline, feed as input the composite, the mask, and the ControlNet guidance

I haven't tested this approach and there are many more ways to do that. If there is more interest in this use case, I could potentially include it in the notebook and propose some solutions!

**Comment by gersonvneto** [comment]
Hey @mikonvergence ,
I'm also trying to combine the images. I'm trying to insert an object into another image instead of the text prompt.

Can you include in the notebook or maybe guide us on what are the ways to achieve that?

Thanks

**Comment by mikonvergence** [comment]
Hi @gersonvneto! Yes, definitely! I can include an example for that in the notebook (or perhaps a separate notebook in the repo) soon.

Can you tell me whether you're more interested in a scenario where
* (a) the pasted object remains exactly as is, and the network harmonises transition between the pasted object and background
* or (b) the pasted object undergoes some changes in colour and lightning to make it work with the rest of the image?

If anyone wants to, they can provide the source images for this operation I will use as the example. Otherwise, I'll try to find something of my own and hope it's relatable to other users!

**Comment by gersonvneto** [comment]
The first scenario (a) is the one that I'm trying to achieve. I believe that the object could have a more realistic look if it fits the image it was inserted into, as is.
The method you proposed had the object pasted looking different, maybe somewhat similar to (b).
![teste](https://user-images.githubusercontent.com/29665944/225695745-27b2b321-492f-450d-b540-2ac6320dcc31.jpeg)
![lamp](https://user-images.githubusercontent.com/29665944/225695824-7f3c42fd-6fa9-4543-8e21-66b3c1a80440.jpeg)

These are two generic pictures, but my goal was to insert the lamp somewhere in the living room

**Comment by themrzmaster** [comment]
I am trying to achieve a similar goal :)

**Comment by mikonvergence** [comment]
![225695745-27b2b321-492f-450d-b540-2ac6320dcc31](https://user-images.githubusercontent.com/13435425/225865108-87c53d6b-74eb-46a0-a07c-ba3ff9ea23a8.jpeg)

I'm still trying to figure out what we would like the model to do.

In the lamp example, there isn't much to do in terms of the mask border, so scenario (a) doesn't seem to be useful in this case. I feel like the changes that would be desired here are adjusted perspective of the object (especially the stand) and the color/lighting changes (so closer to scenario (b)). While the color and lighting can probably taken care of, fixing object perspective is probably something that requires further research.

**Comment by themrzmaster** [comment]
Yes, or sometimes the background of the object is blurry. In my case would be nice to do both things. Incorporate an object in a scene(maybe erasing an old object with the new one) and change it's perspective

**Comment by gersonvneto** [comment]
Yep, that probably was not the best example.
Maybe the exemple below it is a better one. Where the picture have a background and a different lighting.
![image](https://user-images.githubusercontent.com/29665944/225908373-7856f529-71ee-40b0-8859-51d8018dbd30.png)

**Comment by mikonvergence** [comment]
ControlNet does not really do masking of the source image, this should be taken care of before using the tool.

Once you have a masked object you would like to include in the correct location, you could follow the process I described in the first reply.

At some point, I might look into implementing an app that helps with that process if you're interested.

**Comment by themrzmaster** [comment]
I tried folowing your suggestion but I got a bad result. I will organize on a notebook and send it here. Thanks

**Comment by themrzmaster** [comment]
here is the notebook. https://colab.research.google.com/drive/1Egx6VCiIqfOlpzNW40ziwlEV7xwM7_3m#scrollTo=sAEKqQl8ykq- 
maybe my masking was not good?

**Comment by mikonvergence** [comment]
Thanks @themrzmaster - can you also share the images you used in the notebook?

**Comment by themrzmaster** [comment]
https://user-images.githubusercontent.com/852747/228023192-09a4a5b2-a2cf-4efc-b136-07d7a0d0829d.png

https://user-images.githubusercontent.com/852747/228023225-d170a865-9256-4619-b47c-7dff4b248bc2.jpeg)


https://user-images.githubusercontent.com/852747/228023253-cd699104-ce9e-45ef-87fb-3a026b6f9ebf.jpeg

yes! thanks

**Comment by mikonvergence** [comment]
Okay, there are a few issues with the use of the pipeline shown in the notebook:
* The mask image needs to be a binary value that indicates which area must be inpainted
* Your control image seems to be inconsistent with the composite image - notice the edge of the carpet in your control image that overlaps with the table (so some fraction of the edge should actually be invisible in the output image)
* The table needs to be inserted into the process by either (a) masking out only the white background of the pasted rectangle, or by (b) combining the control image of the room with the control image of the table while masking out the entire table region

The tool has not been used correctly, and you will get better results if you use it as intended. However, it also seems like you're working on a more complex problem (related to control-based inpainted, but not exactly the same) and might need to design a solution tailored to your problem.

**Comment by themrzmaster** [comment]
this might be a good way to do it https://arxiv.org/pdf/2303.17546.pdf

**Comment by mikonvergence** [comment]
Yeah, I remember looking through that paper - it's quite neat! It does look like it can bring you closer to the solution to your problem than ControlNetInpaint.

Feel free to post some results in this thread if you manage to get some interesting outputs! :rocket:
