### ISSUE TITLE
RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by yaomilwaukee** [mikonvergence/ControlNetInpaint#10]
RuntimeError                              Traceback (most recent call last)
Cell In[9], line 4
      1 from controlnet_aux import OpenposeDetector
      3 openpose = OpenposeDetector.from_pretrained('lllyasviel/ControlNet')
----> 4 pose_image = openpose(image)
      5 pose_image

File /home/pai/lib/python3.9/site-packages/controlnet_aux/open_pose/__init__.py:83, in OpenposeDetector.__call__(self, input_image, detect_resolution, image_resolution, hand_and_face, return_pil)
     81 H, W, C = input_image.shape
     82 with torch.no_grad():
---> 83     candidate, subset = self.body_estimation(input_image)
     84     hands = []
     85     faces = []

File /home/pai/lib/python3.9/site-packages/controlnet_aux/open_pose/body.py:44, in Body.__call__(self, oriImg)
     42 # data = data.permute([2, 0, 1]).unsqueeze(0).float()
     43 with torch.no_grad():
---> 44     Mconv7_stage6_L1, Mconv7_stage6_L2 = self.model(data)
     45 Mconv7_stage6_L1 = Mconv7_stage6_L1.cpu().numpy()
     46 Mconv7_stage6_L2 = Mconv7_stage6_L2.cpu().numpy()

File /home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File /home/pai/lib/python3.9/site-packages/controlnet_aux/open_pose/model.py:116, in bodypose_model.forward(self, x)
    114 def forward(self, x):
--> 116     out1 = self.model0(x)
    118     out1_1 = self.model1_1(out1)
    119     out1_2 = self.model1_2(out1)

File /home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File /home/pai/lib/python3.9/site-packages/torch/nn/modules/container.py:217, in Sequential.forward(self, input)
    215 def forward(self, input):
    216     for module in self:
--> 217         input = module(input)
    218     return input

File /home/pai/lib/python3.9/site-packages/torch/nn/modules/module.py:1501, in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File /home/pai/lib/python3.9/site-packages/torch/nn/modules/conv.py:463, in Conv2d.forward(self, input)
    462 def forward(self, input: Tensor) -> Tensor:
--> 463     return self._conv_forward(input, self.weight, self.bias)

File /home/pai/lib/python3.9/site-packages/torch/nn/modules/conv.py:459, in Conv2d._conv_forward(self, input, weight, bias)
    455 if self.padding_mode != 'zeros':
    456     return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
    457                     weight, bias, self.stride,
    458                     _pair(0), self.dilation, self.groups)
--> 459 return F.conv2d(input, weight, bias, self.stride,
    460                 self.padding, self.dilation, self.groups)

RuntimeError: GET was unable to find an engine to execute this computation

**Comment by yaomilwaukee** [comment]
I meet this error, How to fix them to working NOT error ? Thanks a lot

**Comment by mikonvergence** [comment]
This is not an issue related to this pipeline and instead to the `OpenPoseDetector`.

Did you check your GPU? Looks like an issue with the call to the conv2d implementation.
