### ISSUE TITLE
Is it possible to train controlnet with this pipeline

### ISSUE THREAD

**Issue by abdelrahmanabdelghany** [mikonvergence/ControlNetInpaint#11]
Hello! I'm trying to train a controlnet with the diffusers train script https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py 
how can i use this pipeline for training with this script

**Comment by mikonvergence** [comment]
Hi, this tool is built on top of pre-trained models, so you should be able to train your own ControlNet model for an inpainting SD model and still use the same pipeline at inference.

However, this repository is focused currently on inference and it is unlikely that I will have time to add example training scripts for the core networks.
