### ISSUE TITLE
Inpainting new "concepts"

### ISSUE THREAD

**Issue by 007prateekd** [mikonvergence/ControlNetInpaint#13]
Great work @mikonvergence!
I have a question that is somewhat related to #1. Say I have a poster image and want to inpaint the face in the poster with a given avatar image like:
<img width="150" alt="Screenshot 2023-06-05 at 3 41 19 PM" src="https://github.com/mikonvergence/ControlNetInpaint/assets/52917805/3a769fd2-c7bc-4c54-8ffd-740ceeb117df">
How can I achieve this given the fact that these avatars are a new "concept" for the LDM? I did try your method mentioned in the issue but it did not work out for me.

**Comment by mikonvergence** [comment]
Hi @007prateekd - this sounds like a more advanced application not supported by this pipeline. A lot of people asked about inserting objects into a scene indeed, but the pipeline in this repo has the simple goal of controlnet-based inpainting, so might not be enough for this specific problem.

**Comment by 007prateekd** [comment]
Hi @mikonvergence
Thanks for the clarification. Do you know of any other ways (preferably diffusion based) which accomplish this?

**Comment by mikonvergence** [comment]
You might want to look into works such as DreamBooth https://dreambooth.github.io if you haven't already. It doesn't do exactly what you were describing, but could be a good start and you can perhaps trace the publications which cited this work - some of them might be even more appropriate.
