### ISSUE TITLE
How to implement without diffusers?

### ISSUE THREAD

**Issue by wolfgangmeyers** [mikonvergence/ControlNetInpaint#14]
I'd like to add support for controlnet inpainting in [ComfyUI](https://github.com/comfyanonymous/ComfyUI) - so that we can use it in the AI horde - but none of our pipelines are using diffusers. Any idea how this can be done with the [RunwayML version of stable diffusion](https://huggingface.co/runwayml/stable-diffusion-v1-5)?

**Comment by mikonvergence** [comment]
Yes, it should be possible if you're only talking about the change of code implementation.

This project is already running on the RunwayML version of SD (`"runwayml/stable-diffusion-inpainting"`), but needs a separate set of weights (`"lllyasviel/sd-controlnet-canny"`) for the ControlNet component.

I am not familiar with ComfyUI, so I can't provide more detailed advice, but yes, as long as you have access to both model weights (inpainting and ControlNet) you should be able to rewrite everything without involvement of diffusers, but it will require quite a bit of manual work. This type of approach will not be provided in this repository but you are of course welcome to edit it in any way and publish as a separate project or make a PR.
