### ISSUE TITLE
The size of tensor a (612) must match the size of tensor b (3) at non-singleton dimension 4

### ISSUE THREAD

**Issue by usamaehsan** [mikonvergence/ControlNetInpaint#18]
Every model except canny is giving this error:

[/content/./ControlNetInpaint/src/pipeline_stable_diffusion_controlnet_inpaint.py](https://localhost:8080/#) in prepare_mask_and_masked_image(image, mask)
    166         mask = torch.from_numpy(mask)
    167 
--> 168     masked_image = image * (mask < 0.5)
    169 
    170     return mask, masked_image

RuntimeError: The size of tensor a (612) must match the size of tensor b (3) at non-singleton dimension 4

**Comment by mikonvergence** [comment]
Has the model occurred in the example notebook too for you?

If not, please compare the tensor shapes with the example notebook to identify the correct shape.
