### ISSUE TITLE
promptless inpainting?

### ISSUE THREAD

**Issue by mikebilly** [mikonvergence/ControlNetInpaint#21]
Is there a way to do promptless inpainting with ControlNet and stable diffusion 1.5 inpainting model?. I want to recreate this https://civitai.com/articles/1907 in colab but don't know how, and I don't want gradio UIs or server because you can't run sd-webui on free Colab and my pc is weak..

**Comment by mikonvergence** [comment]
It is possible to use this pipeline without prompts.

There is also a colab notebook linked in README of the repository:
https://colab.research.google.com/github/mikonvergence/ControlNetInpaint/blob/main/ControlNet-with-Inpaint-Demo-colab.ipynb

For a quick test, this gradio space has been built using this tool and you can check the results when no text prompt is provided:
https://huggingface.co/spaces/mikonvergence/mask-and-sketch
