### ISSUE TITLE
About Training 

### ISSUE THREAD

**Issue by jiangyuhangcn** [mikonvergence/ControlNetInpaint#22]
Hi ! Thanks for your great work! 
I'd like to ask you how to train the model? Is it training both unet  for inpainting and controlnet? Or do you train these two separately?

**Comment by mikonvergence** [comment]
Hi @jiangyuhangcn! Thanks!

So while this repository simply combines previously uncombined model during inference and does not involve training, I can tell you how it was generally done for ControlNet models - separately.

* The paper on ControlNet describes a mechanism to gradually add control to an existing model, like StableDiffusion1.5, without making changes to that core model (this is handled by the zero-convolution mechanism)
* Interestingly, before building this repository, I discovered that a ControlNet model trained for StableDiffusion1.5 (basic text-to-image) would actually work quite okay with a different model - the inpainting variant of StableDiffusion1.5.
* In each case, the ControlNet and the base model are trained separately and combined post-hoc. Standard ControlNet training does require access to some reference model though, but its weights are frozen during the process.

More info in the seminal ControlNet paper: https://arxiv.org/abs/2302.05543

**Comment by jiangyuhangcn** [comment]
> Hi @jiangyuhangcn! Thanks!
> 
> So while this repository simply combines previously uncombined model during inference and does not involve training, I can tell you how it was generally done for ControlNet models - separately.
> 
> * The paper on ControlNet describes a mechanism to gradually add control to an existing model, like StableDiffusion1.5, without making changes to that core model (this is handled by the zero-convolution mechanism)
> * Interestingly, before building this repository, I discovered that a ControlNet model trained for StableDiffusion1.5 (basic text-to-image) would actually work quite okay with a different model - the inpainting variant of StableDiffusion1.5.
> * In each case, the ControlNet and the base model are trained separately and combined post-hoc. Standard ControlNet training does require access to some reference model though, but its weights are frozen during the process.
> 
> More info in the seminal ControlNet paper: https://arxiv.org/abs/2302.05543

Thanks for your quick reply!
